### ISSUE TITLE
help with pg_activity

### ISSUE THREAD

**Issue by KeniaVergara** [dalibo/pg_activity#110]
Hi. I already installed pg_activity, but the user is not postgres, but admin. Please, how do I do in that case to be able to visualize the consumption of cpu and memory of each query that is executed? I would appreciate the help.﻿

**Comment by julmon** [comment]
Hello,

Have you tried : `$ sudo -u admin pg_activity` ?

**Comment by KeniaVergara** [comment]
I explain the procedure I use to use pg_activity, in a console I place sudo su, then its postgres and finally pg_activity -h localhost -U admin -d Bdatos and it throws me the following, FATAL: Must be run with database superuser privileges.
That is, pg_activity only works with the postgres user ???
Please I need help inmediately.

**Comment by binakot** [comment]
As I understand, you have to run `pg_activity` with user that has `superuser privileges`. 

User `postgres` has these privileges by default. That's why you have to use `postgres` (preferable) **OR** you need to add `superuser privileges` to you user `admin` (may be causing security issues).

```sql
ALTER USER admin WITH SUPERUSER;
```

**Comment by KeniaVergara** [comment]
Hello!
I comment again what I did:
ALTER ROLE admin WITH SUPERUSER;
Then, I opened a console and placed:
sudo its
your postgres
psql -h localhost -U admin -d database

Next, in another console, place:
sudo its
your postgres
pg_activity -h localhost -U admin -d database

But, nothing is displayed in the pg_activity. Please help!

**Comment by KeniaVergara** [comment]
Hello!
First, change the super user permissions to the admin user, as shown below:
ALTER ROLE admin WITH SUPERUSER;

I opened a console and placed:
sudo su
su postgres
pg_activity -h localhost -U admin -d database

Then, in another console I placed:
sudo su
su postgres
psql -h localhost -U admin -d database
database= # SELECT * FROM person;

But nothing is shown in pg_activity. Please help!

**Comment by julmon** [comment]
Could you try with : select pg_sleep(10);

**Comment by KeniaVergara** [comment]
Hello! 
I did what you recommended and I do not see the query in pg_activity! I do not know what to do! :(

**Comment by binakot** [comment]
> Hello!
> I did what you recommended and I do not see the query in pg_activity! I do not know what to do! :(

Can you provide more details? May be you can give steps to provide your setup of postgres?

**Comment by KeniaVergara** [comment]
Hello! Will I have to configure postgres for pg_activity to work for me? If so, I do not know how to configure it. I'd appreciate your help.

**Comment by blogh** [comment]
A [FAQ](https://github.com/dalibo/pg_activity#faq) has been added to the README.md to document possible reasons why queries might not show.

If you have more question on this topic feel free to reopen the issue.
