### ISSUE TITLE
Not able to see CPU, Memory ,Read and Writes

### ISSUE THREAD

**Issue by Rakshitha-BR** [dalibo/pg_activity#111]
![image](https://user-images.githubusercontent.com/45063621/55380861-30b54f00-553f-11e9-96b5-b5cdbca4cc4d.png)

Version: pg_activity-1.4.0-1.rhel7.1.noarch

Postgres Version: postgresql10

**Comment by julmon** [comment]
You should run pg_activity with `postgres` system user like this:
```console
$ sudo -u postgres pg_activity
```

**Comment by Rakshitha-BR** [comment]
we are already in postgres user.
then run pg_activity command there.

**Comment by Rakshitha-BR** [comment]
Can you let us know if any tool needs to be installed to collect these stats

**Comment by blogh** [comment]
hi,

**pg_activity** uses the [os](https://docs.python.org/3.8/library/os.html) and [psutils](https://psutil.readthedocs.io/en/latest/) libraries to get the info from the OS / processes. 

**pg_activity** displays the information only if:

* it is launched on the database the PostgreSQL server is running on. The test checks if `inet_server_addr()` is equal to `inet_client_addr()`. [[1](https://www.postgresql.org/docs/10/functions-info.html)]

* the user launching it can access the process / OS infos, the steps are : 
    * connect to the database
    * get the `data_directory` parameter value
    * read the pid file
    * get info from the `postmaster` process

Are you running **pg_activity** :  
* on the server you are running the database ? (it look like it is from your screenshot)
* with the user who is running PostgreSQL ?

Is the following code working (replace POSTGRES_PID with the pid of the postmaster)?
```
$ python3 <<EOF
import psutil  
print(psutil.virtual_memory()) 
p = psutil.Process(POSTGRES_PID)
print(p.cpu_times())
exit()
EOF
```


[1] https://www.postgresql.org/docs/10/functions-info.html
