### ISSUE TITLE
FATAL: Values instance has no attribute 'noappname'

### ISSUE THREAD

**Issue by asaltbde** [dalibo/pg_activity#112]
When I attempt to run pg_activity I see the following error:-

bash-4.1$ pg_activity
**FATAL: Values instance has no attribute 'noappname'**

$ pg_activity --debug
Traceback (most recent call last):
  File "/usr/bin/pg_activity", line 272, in main
    flag = PGAUI.get_flag_from_options(options)
  File "/usr/lib/python2.6/site-packages/pg_activity-1.5.0-py2.6.egg/pgactivity/UI.py", line 621, in get_flag_from_options
    if options.noappname is True:
AttributeError: Values instance has no attribute 'noappname'
FATAL: Values instance has no attribute 'noappname'

I have tried removing and reinstalling, but same error. This works on other similar hosts.

**Versions**
$ pg_activity --version
pg_activity 1.4.0
Postgres 9.6.8
python-psutil-0.6.1-1.el6.x86_64
Centos 6.10

I have installed pg_activity using yum:-

`# yum install pg_activity
Loaded plugins: fastestmirror, security
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirrors.clouvider.net
 * epel: ftp.nluug.nl
 * extras: mirror.econdc.com
 * updates: mirror.mhd.uk.as44574.net
Resolving Dependencies
--> Running transaction check
---> Package pg_activity.noarch 0:1.4.0-1.rhel6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package             Arch           Version                Repository      Size
================================================================================
Installing:
 pg_activity         noarch         1.4.0-1.rhel6          pgdg96          42 k

Transaction Summary
================================================================================
Install       1 Package(s)

Total download size: 42 k
Installed size: 187 k
Is this ok [y/N]: y
Downloading Packages:
pg_activity-1.4.0-1.rhel6.noarch.rpm                     |  42 kB     00:00
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : pg_activity-1.4.0-1.rhel6.noarch                             1/1
  Verifying  : pg_activity-1.4.0-1.rhel6.noarch                             1/1

Installed:
  pg_activity.noarch 0:1.4.0-1.rhel6

Complete!`

**Comment by julmon** [comment]
Hello,

What `pg_activity --version` returns ?

**Comment by julmon** [comment]
Actually, I think you're facing a conflict between versions 1.5 and 1.4. You should remove both, and try to reinstall 1.5 from pypi.

**Comment by Chris-Leeworthy** [comment]
Hi, I work with the original poster, I can tell you we are trying to run pg_activity version 1.4.0

**Comment by blogh** [comment]
Hi, 

"noappname" was introduced in v1.5.0 plus the error states the file "/usr/lib/python2.6/site-packages/pg_activity-1.5.0-py2.6.egg/pgactivity/UI.py". That's why @julmon is proposing this solution.

Could you fix the problem ? Is it working now ?
