### ISSUE TITLE
Make pip installs easier by depending on psycopg2-binary vs psycopg2

### ISSUE THREAD

**Issue by kmoppel** [dalibo/pg_activity#118]
When not using native package managers like APT but "pip" directly then the "psycopg2" package requirement means some other extra packages are needed. psycopg2-binary is API compatible with psycopg2 and has no extra dependencies.

There might be some caveats though, so would make sense to read this discussion - https://github.com/psycopg/psycopg2/issues/674

**Comment by blogh** [comment]
Hi,

Thank you for reporting this.
We have decided to use the same approach as [patroni](https://github.com/zalando/patroni/pull/102) and [temboard](https://github.com/dalibo/temboard/commit/2ffa8777123504e8c2d01fb16fb058e6d37c4ad0). We will remove psycopg2 from setup.py and document that the rpm should be installed beforehand.

Thx
Benoit

**Comment by blogh** [comment]
Done as stated above.
