### ISSUE TITLE
How to Use pg_activity tools for managed database (postgreSQL from RDS amazon and RDS alyun)

### ISSUE THREAD

**Issue by edenramba** [dalibo/pg_activity#143]
Hi 

I tried to use this tool for RDS posgreSQL Alibaba version **PostgreSQL 10.0**. As we know that we don't have root/super user privilege if we use RDS instance, while pg_activity need this privilege to execute the command.

Here is the privilege from RDS instance that I have.
![image](https://user-images.githubusercontent.com/50127866/85528476-23015300-b636-11ea-8fc2-b113afa0884b.png)

And here is the issue that comes up.
![image](https://user-images.githubusercontent.com/50127866/85528770-8c816180-b636-11ea-8ca6-004454db4b26.png)

Any alternative for my issue or did you guys experience the same issue ?

**Comment by blogh** [comment]
Hi, 

Did you try the `--rds` switch ?

Benoit

**Comment by edenramba** [comment]
Oh thanks.

It works, I did not read the option before. 

:)
