### ISSUE TITLE
Add support for url-like connection strings

### ISSUE THREAD

**Issue by piotrkilczuk** [dalibo/pg_activity#151]
psql allows you to connect with the following syntax:

```bash
psql postgresql://user:pass@host/db
```

It would be helpful if pg_activity provided the same ability.

Especially useful if you store your connection strings in some kind of environment variables.

**Comment by dlax** [comment]
This got fixed by allowing libpq's connection string to be passed as an argument by 73a71c56a44e30d105b63693cdf99eaec364c960 and is available in pg_activity 2.0.0.
