### ISSUE TITLE
can't launch release 2.0.0 on redhat7 system

### ISSUE THREAD

**Issue by sebastienruiz** [dalibo/pg_activity#166]
Hi,

After installing pg_activity rpm (from https://ftp.postgresql.org/pub/repos/yum/common/redhat/rhel-7-x86_64/) :
(as root)
yum install -y pg_activity-2.0.0-1.rhel7.noarch.rpm
...
...

Installed:
  pg_activity.noarch 0:2.0.0-1.rhel7

Dependency Installed:
  python3.x86_64 0:3.6.8-18.el7                python3-libs.x86_64 0:3.6.8-18.el7      python3-pip.noarch 0:9.0.3-8.el7    python3-psycopg2.x86_64 0:2.8.5-2.rhel7
  python3-setuptools.noarch 0:39.2.0-10.el7    python36-psutil.x86_64 0:5.6.7-1.el7

Complete!

When i launch pg_activity (as postgres user), i've got this error :
pg_activity 
Traceback (most recent call last):
  File "/bin/pg_activity", line 35, in <module>
    from blessed import Terminal
ModuleNotFoundError: No module named 'blessed'

(same error occur with user root).

Thank for your help.

**Comment by dlax** [comment]
Yes, the RPM packages from pgdg is apparently broken. I reported the issue at https://redmine.postgresql.org/issues/6167.

**Comment by dlax** [comment]
In the meantime, you can install the following packages to make pg_activity working: python36-attrs, python36-blessed, python36-humanize. Some come from EPEL.

**Comment by sebastienruiz** [comment]
yes that's what i tried on 2 servers;
First one works fine.
But the second failed :
(i don't understand why)

pg_activity
Traceback (most recent call last):
  File "/bin/pg_activity", line 295, in <module>
    ui.main(term, dataobj, host, options, dsn)
  File "/usr/lib/python3.6/site-packages/pgactivity/ui.py", line 227, in main
    width=width,
  File "/usr/lib/python3.6/site-packages/pgactivity/views.py", line 525, in screen
    width=width,
  File "/usr/lib/python3.6/site-packages/pgactivity/views.py", line 124, in wrapper
    for line in func(term, *args, **kwargs):
  File "/usr/lib/python3.6/site-packages/pgactivity/views.py", line 404, in processes_rows
    query_lines = [wrapped_lines[0]] + term.wrap(
IndexError: list index out of range

there are the installed packages on the second one :
python36-six-1.14.0-2.el7.noarch
python3-setuptools-39.2.0-10.el7.noarch
python3-pip-9.0.3-8.el7.noarch
python36-pytest-2.9.2-4.el7.noarch
python3-psycopg2-2.8.5-2.rhel7.x86_64
python3-libs-3.6.8-18.el7.x86_64
python36-py-1.4.32-2.el7.noarch
python36-attrs-17.4.0-4.el7.noarch
python36-psutil-5.6.7-1.el7.x86_64
python3-3.6.8-18.el7.x86_64
python36-humanize-0.5.1-8.el7.noarch
python36-wcwidth-0.2.3-1.el7.noarch
python36-blessed-1.17.10-1.el7.noarch
pg_activity-2.0.0-1.rhel7.noarch

NOTA : if i try to install python36-psycopg2.x86_64 instead of python3-psycopg2-2.8.5-2.rhel7.x86_64, pg_activity package won't install.

**Comment by sebastienruiz** [comment]
Hi,

I've get the new package for pg_activity from  https://ftp.postgresql.org/pub/repos/yum/common/redhat/rhel-7-x86_64/

I've successfully installed it :

Installed:
  pg_activity.noarch 0:2.0.0-2.rhel7

Dependency Installed:
  python3-psycopg2.x86_64 0:2.8.5-2.rhel7   python36-attrs.noarch 0:17.4.0-4.el7   python36-blessed.noarch 0:1.17.10-1.el7   python36-humanize.noarch 0:0.5.1-8.el7
  python36-psutil.x86_64 0:5.6.7-1.el7

Complete!


but i still hace those errors :

pg_activity
Traceback (most recent call last):
  File "/bin/pg_activity", line 295, in <module>
    ui.main(term, dataobj, host, options, dsn)
  File "/usr/lib/python3.6/site-packages/pgactivity/ui.py", line 227, in main
    width=width,
  File "/usr/lib/python3.6/site-packages/pgactivity/views.py", line 525, in screen
    width=width,
  File "/usr/lib/python3.6/site-packages/pgactivity/views.py", line 124, in wrapper
    for line in func(term, *args, **kwargs):
  File "/usr/lib/python3.6/site-packages/pgactivity/views.py", line 404, in processes_rows
    query_lines = [wrapped_lines[0]] + term.wrap(
IndexError: list index out of range

**Comment by sebastienruiz** [comment]
NOTA : it's work fine on another server with pg_activity.noarch 0:2.0.0-2.rhel7
i don't understand.

**Comment by dlax** [comment]
That other issue got fixed in v2.0.2, released on Friday. I just asked for packaging update at https://redmine.postgresql.org/issues/6172

**Comment by sebastienruiz** [comment]
Hi, just for feedback : new package pg_activity-2.0.3-1.rhel7.noarch.rpm works fine.
Many thanks for your job.
