### ISSUE TITLE
pg_activity -h connection to AWS RDS PostgreSQL is failing

### ISSUE THREAD

**Issue by SCI-sksaha** [dalibo/pg_activity#167]
FATAL: Must be run with database superuser privileges.

Any option to bypass this error? A subset of data displayed is acceptable.

Thanks & Regards
.... Sushanta

**Comment by fabiogeiss** [comment]
Has a --rds parameter
.
run pg_activity -U <your_user> -h <your_RDS_DNS_HOST> --rds

**Comment by SCI-sksaha** [comment]
That worked! Thanks a lot!

.... Sushanta
