### ISSUE TITLE
Fails to install on Ubuntu 20.04.1 LTS / python 3.8.5

### ISSUE THREAD

**Issue by maiku41** [dalibo/pg_activity#169]
Using 'sudo apt install pg-activity' results in three syntax warnings in UI.py ("is not" with a literal.  Did you mean "!="?).

Attempting to run pg_activity after this results in:
ImportError: cannot import name 'UI' from 'pgactivity'.

**Comment by dlax** [comment]
It looks like a packaging issue. The Debian/Ubuntu package is out of date at the moment (version 1.6.2 as compared to 2.0.2 here). I'd suggest to wait until the package gets updated in Debian or install `pg_activity` from `pip` if this is possible for you.

**Comment by maiku41** [comment]
Thanks,

Installing from pip seemed to complete without issues, but the command pg_activity results in  "Command 'pg_activity' not found, but can be installed with...".

I've no experience using pip, so not sure where to look from here.

**Comment by dlax** [comment]
I understand that pip might not be an option for everyone. We'll see if we can provide a Debian package in the meantime for such situations; I'll report back here later on.

**Comment by maiku41** [comment]
Thank you.  Will watch for that.

**Comment by dlax** [comment]
I attached a Debian package to [release 2.0.3](https://github.com/dalibo/pg_activity/releases/tag/v2.0.3) at https://github.com/dalibo/pg_activity/releases/download/v2.0.3/pg-activity_2.0.3-0dlb1buster-1_all.deb; it should work too on ubuntu 20.04.

This package is provided for convenience, until the official package from Debian/Ubuntu gets updated, the latter being preferable in general.

**Comment by maiku41** [comment]
That works.  Thanks!
