### ISSUE TITLE
 min-duration  and duration-mode don't work

### ISSUE THREAD

**Issue by andyczerwonka** [dalibo/pg_activity#177]
I wasn't able to set these. I get an error when trying to.

--min-duration
--duration-mode

**Comment by dlax** [comment]
Please provide more detail about the error you get (output from your terminal, for instance). I cannot reproduce.

**Comment by andyczerwonka** [comment]
Apologies, I installed it via `apt`, which gave me a very old version. I've removed it and installed via `pip` and it's working.

**Comment by blogh** [comment]
Great, thx for the feedback.
