### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 148-152: ordinal not in range(128)

### ISSUE THREAD

**Issue by bkalpa9** [dalibo/pg_activity#181]
```console
$ sudo -iu postgres pg_activity
Traceback (most recent call last):
  File "/usr/bin/pg_activity", line 296, in <module>
    ui.main(term, dataobj, host, options, dsn)
  File "/usr/lib/python3.6/site-packages/pgactivity/ui.py", line 227, in main
    width=width,
  File "/usr/lib/python3.6/site-packages/pgactivity/views.py", line 528, in screen
    width=width,
  File "/usr/lib/python3.6/site-packages/pgactivity/views.py", line 125, in wrapper
    print(shorten(term, line, width) + term.clear_eol)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 148-152: ordinal not in range(128)
```

**Comment by dlax** [comment]
Can you provide the output of `sudo -iu postgres locale` command?

**Comment by bkalpa9** [comment]
sudo -iu postgres locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

**Comment by dlax** [comment]
Thanks; it's not clear to me what the problem is. Can you report back the output of the following commands?
```
sudo -iu postgres python3 -c 'import locale; print(locale.getpreferredencoding())'
sudo -iu postgres python3 -c 'import sys; print(sys.stdout)'
```

Also, does the problem also occur if you run pg_activity using another user?

**Comment by bkalpa9** [comment]
`sudo -iu postgres python3 -c 'import locale; print(locale.getpreferredencoding())'
-bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
ANSI_X3.4-1968
`

`sudo -iu postgres python3 -c 'import sys; print(sys.stdout)'
-bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
<_io.TextIOWrapper name='<stdout>' mode='w' encoding='ANSI_X3.4-1968'>`

**Comment by dlax** [comment]
It may be that you system is missing the 'C.UTF-8' locale (you may see 
it's not listed with 'locale -a').

So I'd suggest to either install it or try to force using 'en_US.UTF-8' 
as LC_ALL and LANG in the environment of the 'postgres' user.

**Comment by bkalpa9** [comment]
Thanks, installing  glibc helped.
