### ISSUE TITLE
Reconnect when the server restarts

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/pg_activity#184]
When a server restarts, pg_activity fails.

I'd like to see reconnect itself alone by default
( provided there is no option like eg  ''--timeout'' ou ''--no-retry'', but I'm not sure they would be so useful).

**Comment by dlax** [comment]
Which version are you using? From at least version 1.5, pg_activity should try to reconnect. (Currently, it tries to reconnect 3 times, waiting 5s in between.)

**Comment by Krysztophe** [comment]
Version :   2.0.0~a3-0dlb1buster-1 500

A database restart may take much more than 15 s!!

Anyway, I see it fail as soon as I stop the instance (clean shutdown or not):
```
Traceback (most recent call last):
  File "/usr/bin/pg_activity", line 253, in <module>
    ui.main(options)
  File "/usr/lib/python3/dist-packages/pgactivity/ui.py", line 169, in main
    pg_db_info = data.pg_get_db_info(
  File "/usr/lib/python3/dist-packages/pgactivity/data.py", line 256, in pg_get_db_info
    cur.execute(
  File "/usr/lib/python3/dist-packages/psycopg2/extras.py", line 146, in execute
    return super(DictCursor, self).execute(query, vars)
psycopg2.errors.AdminShutdown: terminating connection due to administrator command
la connexion au serveur a été coupée de façon inattendue
        Le serveur s'est peut-être arrêté anormalement avant ou durant le
        traitement de la requête.
```

**Comment by dlax** [comment]
> Version :   2.0.0~a3-0dlb1buster-1 500

That's an old pre-release, only made available for testing in -labs 
repository (arguably, we should drop it from there); and reconnect was 
indeed missing in that release. You can get a more recent package at 
https://github.com/dalibo/pg_activity/releases/tag/v2.0.3.


> A database restart may take much more than 15 s!!

Maybe. We can certainly change that, what would you suggest? (We can 
even waiting indefinitely, I think.)

**Comment by Krysztophe** [comment]
That's much better, thank you!

+1 for dropping outdated versions from apt.dalibo.org, that leads only to confusion.

**Comment by dlax** [comment]
> +1 for dropping outdated versions from apt.dalibo.org, that leads only to confusion.

It's dropped now.
