### ISSUE TITLE
[feature request] Provide CLI flag to truncate long queries to a given width

### ISSUE THREAD

**Issue by kigster** [dalibo/pg_activity#189]
We use very long auto-generated queries and on a 300-row terminal, only 2-3 queries fit when rendered completely. We usually know which query this is from the first 100-200 characters, so it would be great if one could pass eg:

```
pg_activity [ --truncate-query-at=200 ]
```

This would only show the first 200 characters of the query itself.

Another useful flag would truncate the query to one line only, depending on the terminal width and columns shown:

```
pg_activity [ -w | --truncate-query  ]
```

Of course, you can also add eg the number of lines etc, but I think the terminal width and a custom length are the two most common use-cases.

**Comment by kigster** [comment]
And by the way, I was excited to find this tool as I'm the author of the BASH version that unlike `pg_activity`, can show up to three databases at once and auto-truncates the query.

However my tool does not display the helpful per-database statistics such as TPS that pg_activity shows, and is generally much more primitive.

https://github.com/kigster/bashmatic#example-e-database-utilities-dbtop

**Comment by dlax** [comment]
There's already a `--verbose-mode` option, which you can pass 1 to have queries truncated to fit on a single line; this display mode can be changed when pg_activity is running by hitting the `v` key to cycle available modes (full, truncated, wrapped). Does that fit your use case?

**Comment by dlax** [comment]
Agreed; we should rename it.
