### ISSUE TITLE
Num version don't match libpq format for version >10

### ISSUE THREAD

**Issue by pgiraud** [dalibo/pg_activity#199]
https://github.com/dalibo/pg_activity/blob/4ad400eceedaac645241d64c640adef221e0ce12/pgactivity/data.py#L57

As per documentation in https://www.postgresql.org/docs/current/libpq-status.html#LIBPQ-PQSERVERVERSION, version 11.9 should return 110009.

**Comment by blogh** [comment]
Thx for the report will look into it today.

**Comment by blogh** [comment]
Fxed in #200.
There might be a bug in pgtoolkit for "PostgreSQL  9.6devel" interpreted as a non devel version with number "906".

**Comment by blogh** [comment]
merged (at last)
