### ISSUE TITLE
Wrong version of Python requirement on labs.dalibo.com

### ISSUE THREAD

**Issue by daftaupe** [dalibo/pg_activity#226]
Hi,

not sure that it's the right place to report that but on https://labs.dalibo.com/pg_activity the required Python version is wrong as on this repo it's listed as Python 3.6 minimum.

I guess this old version being displayed could prevent some people from even giving a try at the project and that's too bad.

**Comment by blogh** [comment]
Sorry this issue got completely forgotten. 

We just pointed the dalibo labs page to the github page and removed most of the information there.

Thanks for pointing it out !
