### ISSUE TITLE
broken when using -U parameter

### ISSUE THREAD

**Issue by fabiogeiss** [dalibo/pg_activity#229]
I updated pg_activity and it broke

I have an exclusive superuser role to use with pg_activity. Before update, it works fine, but now when I try to use it, this error happens:

```
[root@local]# pg_activity -U myrole
pg_activity: FATAL: database "myrole" does not exist
[root@local]#
```

My old version was 2.0.5

**Comment by blogh** [comment]
Hi, 

What's the database name you are trying to connect to ?

Benoit

**Comment by blogh** [comment]
We reverted to libpq's default behavior of using `dbname` = `username` when `dbname` is not provided.
Before, it was defaulted to database **postgres**.

It should work with one of thoses :

```
pg_activity -U myrole -d postgres                 #  provide the dbname as an option
pg_activity "dbname=postgres  user=myrole"        #  provide the dbname in the connection string
PGDATABASE=postgres pg_activity -U myrole         # provide the dbname in the environment variable.
```

**Comment by fabiogeiss** [comment]
Hi

Thanks for replying. 
I understood and changed my aliases. 

But, before, when I didn't inform the database, pg_activity showed the activity of all databases in the cluster. Now I can't do it anymore.

How can I view this in this new version? Otherwise, there is no more sense in having the column "database" on the screen.

**Comment by fabiogeiss** [comment]
Hi !

Thanks for answer!

I changed my aliases. 

nice!
