### ISSUE TITLE
Invalid character on interface

### ISSUE THREAD

**Issue by fabiogeiss** [dalibo/pg_activity#230]
Apparently the PIPE was replaced by an unusual character, breaking the interface.
Please go back to PIPE. Works great and doesn't break the screen

![image](https://user-images.githubusercontent.com/388463/124181081-726d3100-da8b-11eb-9f38-3634edcd74b9.png)

**Comment by blogh** [comment]
Hi,

It was modified in [this commit](https://github.com/dalibo/pg_activity/commit/c828f67ada70beb6559e09ed6a26c66d3aa0e816) and should be a [blue bold dot](https://blessed.readthedocs.io/en/latest/colors.html).

Which Os are you running ?

**Comment by fabiogeiss** [comment]
> 
> 
> Hi,
> 
> It was modified in [this commit](https://github.com/dalibo/pg_activity/commit/c828f67ada70beb6559e09ed6a26c66d3aa0e816) and should be a [blue bold dot](https://blessed.readthedocs.io/en/latest/colors.html).
> 
> Which Os are you running ?

CentOs 7

**Comment by dlax** [comment]
We're not really using something fancy here, it's just a '⋅' (U+22C5 
unicode character).

So your terminal might be able to display unicode characters, which is 
quite odd these days. Can't you use another terminal or configure it 
properly?

**Comment by fabiogeiss** [comment]
I needed to change the default  terminal's font.  That's ok ! 

May you can change to a more normal char. Maybe the problem is not the character itself, but that it has color ... I'm just thinking about .

BTW, thanks dlax

**Comment by dlax** [comment]
Will address in #357
