### ISSUE TITLE
[2.1.5][BUG] Unsupported Operand Type Error

### ISSUE THREAD

**Issue by sagar-bista** [dalibo/pg_activity#233]
Issue: not able to run pg_activity

Command to reproduce issue :  pg_activity

Traceback (most recent call last):
  File "/home/user/.local/bin/pg_activity", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.8/site-packages/pgactivity/cli.py", line 293, in main
    ui.main(term, dataobj, host, options, dsn)
  File "/home/user/.local/lib/python3.8/site-packages/pgactivity/ui.py", line 152, in main
    pg_db_info = data.pg_get_db_info(
  File "/home/user/.local/lib/python3.8/site-packages/pgactivity/data.py", line 251, in pg_get_db_info
    float(ret["total_size"] - prev_db_infos["total_size"])
TypeError: unsupported operand type(s) for /: 'float' and 'decimal.Decimal'

Python Version: Python 3.8.10
pg_activity version: pg-activity==2.1.5
pip version: pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
OS: Ubuntu 20.04.2 LTS

**Comment by dlax** [comment]
What is the version of postgresql on the server?
Can you also share the version of psycopg2 (`pip list | grep psycopg2`)?

**Comment by sagar-bista** [comment]
psycopg2==2.8.6
PostgreSQL version: 13

**Comment by sagar-bista** [comment]
It's working after i modify line 248 and 252

            try:
                tps = int(
                    (ret["no_xact"] - prev_db_infos["no_xact"])
                    / **int**((ret["timestamp"] - prev_db_infos["timestamp"]))
                )
                size_ev = float(
                    float(ret["total_size"] - prev_db_infos["total_size"])
                    / **floa**t((ret["timestamp"] - prev_db_infos["timestamp"]))
                )
            except ZeroDivisionError:
                pass
