### ISSUE TITLE
unable to get pg_activity running on RHEL8 / PG12

### ISSUE THREAD

**Issue by sbec67** [dalibo/pg_activity#235]
Hi,

I was trying to get pg_activity running on RHEL8 / PG12 / Python 3.6.8

sudo python3 setup.py install runs smoothly without any error message

sudo -u postgres /usr/local/bin/pg_activity -U postgres 

shows

`Traceback (most recent call last):
  File "/usr/local/bin/pg_activity", line 11, in <module>
    load_entry_point('pg-activity==2.1.5', 'console_scripts', 'pg_activity')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/pg_activity-2.1.5-py3.6.egg/pgactivity/cli.py", line 9, in <module>
    from psycopg2.errors import OperationalError
ModuleNotFoundError: No module named 'psycopg2'
`
any help would be appreciated

**Comment by blogh** [comment]
Hi,

It looks like you're missing psycopg2 (version 2.8 or higher is required).

see: https://github.com/dalibo/pg_activity/issues/118 for more info.

**Comment by sbec67** [comment]
i got
`Installed Packages
python2-psycopg2.x86_64                                                                                                     2.7.5-7.module+el8.1.0+3111+de3f2d8e                                                                                              @AppStream
python3-psycopg2.x86_64                                                                                                     2.7.5-7.el8                                                                                                                       @rhel-8-AppStream
python38-psycopg2.x86_64                                                                                                    2.8.4-4.module+el8.4.0+8888+89bc7e79                                                                                              @rhel-8-AppStream
python39-psycopg2.x86_64                                                                                                    2.8.6-2.module+el8.4.0+9822+20bf1249                                                                                              @rhel-8-AppStream`

installed - 

run the setup.py again 

still see : 
`[ sysprog@10.21.101.71 ~/pg_activity-2.1.5 ] $  /usr/local/bin/pg_activity --help
Traceback (most recent call last):
  File "/usr/local/bin/pg_activity", line 11, in <module>
    load_entry_point('pg-activity==2.1.5', 'console_scripts', 'pg_activity')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/pg_activity-2.1.5-py3.6.egg/pgactivity/cli.py", line 9, in <module>
    from psycopg2.errors import OperationalError
ModuleNotFoundError: No module named 'psycopg2.errors'
[ sysprog@10.21.101.71 ~/pg_activity-2.1.5 ] $
`
any further help ?

**Comment by blogh** [comment]
I think you have to install the rpm or `pip install psycopg2-binary`.

**Comment by sbec67** [comment]
`[ sysprog@10.21.101.71 ~ ] $  pip install psycopg2-binary
Requirement already satisfied: psycopg2-binary in /usr/lib64/python2.7/site-packages
[ sysprog@10.21.101.71 ~ ] $
`
on RHEL8 i cant find an rpm
`[ sysprog@10.21.101.71 ~ ] $  sudo dnf install psycopg2-binary
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.

Last metadata expiration check: 0:04:15 ago on Tue 17 Aug 2021 08:17:04 AM CEST.
No match for argument: psycopg2-binary
Error: Unable to find a match: psycopg2-binary
`
does pg_activity support RHE8 / PostgreSQL12 ?

**Comment by blogh** [comment]
It does support PostgreSQL 12.
I am downloading a RHE8 binary right now.

**Comment by blogh** [comment]
Just did it that way :
```
$ cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.4 (Ootpa)
$ sudo dnf install git python3
$ git clone https://github.com/dalibo/pg_activity.git
$ cd pg_activity
$ python3 -m venv ~/test
$ source ~/test/bin/activate
(test) $ pip install --upgrade pip
(test) $ pip install .
(test) $ pg_activity --help
Traceback (most recent call last):
  File "/home/benoit/test/bin/pg_activity", line 5, in <module>
    from pgactivity.cli import main
  File "/home/benoit/test/lib64/python3.6/site-packages/pgactivity/cli.py", line 8, in <module>
    from psycopg2.errors import OperationalError
ModuleNotFoundError: No module named 'psycopg2'
(test) $ pip install psycopg2-binary
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.1-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.4 MB)
     |████████████████████████████████| 3.4 MB 4.4 MB/s 
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.1
(test) $ pg_activity --help
Usage: pg_activity [options] [connection string]

htop like application for PostgreSQL server activity monitoring.

Options:
  --version             show program's version number and exit
 ...
```

**Comment by sbec67** [comment]
worked for me also - thanks a lot !!!!!

**Comment by blogh** [comment]
Glad to hear that worked !

**Comment by dlax** [comment]
For end users, installing from pip or setup.py is not recommended. On 
RHEL, you should use https://yum.postgresql.org/ where a RPM package for 
pg-activity is available.
