### ISSUE TITLE
the latest release is very slow

### ISSUE THREAD

**Issue by bagafoot** [dalibo/pg_activity#239]
I'm using pg_activity 2.2.1 release, when scroll up/down its response quite slow compared to previous releases.
It is not big deal but a little bit annoying.

**Comment by dlax** [comment]
Which previous release(s) do you compare to?

**Comment by bagafoot** [comment]
1.5

**Comment by dpiscitelli** [comment]
Hello,

Sadly, I have to confirm this point, slower than 1.6 in my environments

**Comment by blogh** [comment]
With the PR #247, scrolling should work properly.
I think I found why it's slow and will address it in a separate PR.

**Comment by blogh** [comment]
The performance should be better with #249.
There is still a bug related to scrolling with wrapping / ident + wrapping.

**Comment by dlax** [comment]
I think we can close this issue as performance problems have been resolved. The scrolling issues will be tracked in #260.
