### ISSUE TITLE
Python 3.9: AttributeError: 'Values' object has no attribute 'querydisplaymode'

### ISSUE THREAD

**Issue by pietromingo** [dalibo/pg_activity#245]
I'm running ubuntu 21.10 and Python3.9, pg_activity 2.2.1, i get this error:

`Traceback (most recent call last):
  File "/usr/bin/pg_activity", line 321, in <module>
    ui.main(term, dataobj, host, options, dsn)
  File "/home/pietro/.local/lib/python3.9/site-packages/pgactivity/ui.py", line 39, in main
    query_display_mode=int(options.querydisplaymode),
AttributeError: 'Values' object has no attribute 'querydisplaymode'`

**Comment by dlax** [comment]
> `File "/usr/bin/pg_activity" ...`

and 

> `File "/home/pietro/.local/lib/python3.9/site-packages/pgactivity/ui.py" ...`

indicate that you are mixing a system installation (`/usr/bin`) with a local one (in `/home/pietro/.local/`), probably coming from a `pip install --user`. 

Try `pip3 uninstall pg_activity`, as user `pietro`, to remove the local installation.

**Comment by pietromingo** [comment]
> > `File "/usr/bin/pg_activity" ...`
> 
> and
> 
> > `File "/home/pietro/.local/lib/python3.9/site-packages/pgactivity/ui.py" ...`
> 
> indicate that you are mixing a system installation (`/usr/bin`) with a local one (in `/home/pietro/.local/`), probably coming from a `pip install --user`.
> 
> Try `pip3 uninstall pg_activity`, as user `pietro`, to remove the local installation.

Thank you very much, sorry if I wasted your time!
