### ISSUE TITLE
Run pg_activity without a superuser privilege

### ISSUE THREAD

**Issue by Raymondmax** [dalibo/pg_activity#277]
Hello, as the title says, how can I run pg_activity without a superuser privilege, I understand that we can alter a normal user to have that privilege, but it may cause a security issue.

**Comment by dlax** [comment]
You can use any postgres role allowed to LOGIN. The SUPERUSER capability 
will only make it possible to retrieve system information (in the header 
in particular). But otherwise, these just won't be displayed.

**Comment by blogh** [comment]
A superuser is required when we don't use the `--rds` option. ( see `pg_connect` in `data.py`)
On the master branch, it might not work at all because I failed to test with this option ... (#278)

**Comment by dlax** [comment]
Oh. Indeed, I missed that.

Perhaps we should rename this --rds option after all...

**Comment by blogh** [comment]
The rds option is still useful because it skips the database `rdsadmin`.
Filtering out this database should be possible with the new FILTER option though.

**Comment by blogh** [comment]
from the docs of pg_database_size : 

> Computes the total disk space used by the database with the specified name or OID. To use this function, you must have CONNECT privilege on the specified database (which is granted by default) or be a member of the pg_read_all_stats role.

**Comment by Raymondmax** [comment]
I add rds option and it works, thank you all for the help!

**Comment by blogh** [comment]
Hi, the next version will allow to use the app without superuser privileges.
