### ISSUE TITLE
2.3.0 fails to run on RHEL 8 and 7

### ISSUE THREAD

**Issue by devrimgunduz** [dalibo/pg_activity#285]
Hi,

pg_activity 2.3.0 fails to run against RHEL 7 and 8. I was reported that fields_dict was added on attr 18.1.0: https://www.attrs.org/en/stable/api.html#attrs.fields_dict

However, on RHEL 7:  python36-attrs-17.4.0-4.el7.noarch
RHEL 8: python3-attrs-17.4.0-6.el8.noarch

Below is the error message. Anything you can do? 

Thanks! Devrim

Traceback (most recent call last):
  File "/usr/bin/pg_activity", line 11, in <module>
    load_entry_point('pg-activity==2.3.0', 'console_scripts', 'pg_activity')()
  File "/usr/lib/python3.6/site-packages/pgactivity/cli.py", line 276, in main
    filters = types.Filters.from_options(options.filters)
  File "/usr/lib/python3.6/site-packages/pgactivity/types.py", line 139, in from_options
    fields = attr.fields_dict(cls)
AttributeError: module 'attr' has no attribute 'fields_dict'

**Comment by dlax** [comment]
Released version 2.3.1 fixing this issue.

**Comment by devrimgunduz** [comment]
Hi,

Thanks for the quick fix! 

Cheers, Devrim
