### ISSUE TITLE
Error while running on pg14

### ISSUE THREAD

**Issue by fabiogeiss** [dalibo/pg_activity#288]
Recently I upgraded my db to postgres 14 and since this pg_activity crashes after some minutes, with this error:

![image](https://user-images.githubusercontent.com/388463/166234311-cb5d7eef-c0ab-4b5d-80c8-7fbc16b12cd3.png)

BTW, I have an alias to pg_activity: alias pg_activity='pg_activity -U <myuser> -h localhost -p <my port> --no-database --verbose-mode=1 --no-db-size -d <my database>'

**Comment by blogh** [comment]
Hi,

I just merged #290. does it fix your problem ?

**Comment by fabiogeiss** [comment]
YES!!! I haven't seen it ! Thanx @blogh  !
