### ISSUE TITLE
processes sort with parallel worker is broken

### ISSUE THREAD

**Issue by dlax** [dalibo/pg_activity#297]
See discussion at #291.

From postgres 13, maybe we could rely on `leader_pid` column of `pg_stat_activity` view as first sort step on SQL side?

**Comment by kmoppel-cognite** [comment]
FYI - just remembered that I've seen actually cases where parent `pid` was higher than background worker / child `pid`...so this code here can deliver wrong results still https://github.com/dalibo/pg_activity/pull/291/files#diff-c7ba7b4a3a801c37989b9ac81ece8995e3154d2f67325272f24877b5e730cf65R219-R222

**Comment by kmoppel-cognite** [comment]
> @kmoppel-cognite what do you think about sorting/filtering in paused/interactive mode ?

@blogh For me personally I've never had the need for such extra features, I've just used "pause" to freeze the UI to be able to copy some SQL or kill some PIDs. And there's also the new `--filter` syntax, so I'd personally KISS and try to reduce UI logic / code as much as possible.
