### ISSUE TITLE
Add a shortcut to copy a query

### ISSUE THREAD

**Issue by nogweii** [dalibo/pg_activity#311]
I'd like to easily and quickly grab a copy of a query that's been running for a long time in order to save it off before killing it. Even better if it was a keyboard shortcut that copied to my system clipboard.

Perhaps [pyperclip](https://pypi.org/project/pyperclip/) can be of use?

**Comment by dhenson02** [comment]
I second this request!

**Comment by blogh** [comment]
I have a patch to "zoom" on the query and display it full screen.
I didn't think about the clipboard. I will look into it.
Thanks for the issue.

**Comment by dlax** [comment]
> Perhaps [pyperclip](https://pypi.org/project/pyperclip/) can be of use?

I'm not sure this would be a good fit for pg_activity as it seems to me that pyperclip relies on graphical selections (e.g. xsel) whereas pg_activity is often used without a graphical environment (i.e. remotely through, e.g. ssh or on using `sudo -iu postgres`).
