### ISSUE TITLE
Help for installation pg_activity 3.0.1

### ISSUE THREAD

**Issue by egaultier** [dalibo/pg_activity#322]
Hi 

I want install pg_activity 3.0.1 on RheL 8.6

I have this error : 
![image](https://user-images.githubusercontent.com/67147948/193278930-49a5ab5c-71f7-4bfe-ae75-e41f689044d1.png)

I install python39 with yum command 
sudo yum install python39

![image](https://user-images.githubusercontent.com/67147948/193279120-f9500303-667b-46f1-a607-c8a6a92b1d9c.png)

I have the same error when I want to install yet pg_activity 3.0.1

Thx for your help.

Emmanuel

**Comment by blogh** [comment]
Hi, 

Thanks for the report.
There is a packaging problem on Redhat 8 (see https://github.com/dalibo/pg_activity/issues/319)

**Comment by blogh** [comment]
The install with pip works (I you have the required access)

**Comment by bagafoot** [comment]
I have similar error on Rocky 9

Last metadata expiration check: 0:24:52 ago on Thu 10 Nov 2022 05:07:34 PM +03.
Error:
 Problem: cannot install the best candidate for the job
  - nothing provides python3.9dist(blessed) needed by pg_activity-3.0.0-1.rhel9.noarch
  - nothing provides python3-blessed needed by pg_activity-3.0.0-1.rhel9.noarch
  - nothing provides python3-humanize >= 2.6.0 needed by pg_activity-3.0.0-1.rhel9.noarch
  - nothing provides python3.9dist(humanize) >= 2.6 needed by pg_activity-3.0.0-1.rhel9.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

**Comment by mikelolasagasti** [comment]
@bagafoot if release 2.3.1 is enough for you, it should be available in EPEL9 next week. You can test the build with this update https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2022-89a5b2ec98

**Comment by krisavi** [comment]
pg_activity 3.x.x is giving errors on Almalinux as well. I think it was not the best to publish such package to PGDG that requires dependencies that will not be provided so soon to AppStream RPM repository:
```
nothing provides python3-attrs >=18.1 needed by pg_activity-3.1.1-1.rhel8.noarch
nothing provides python3-humanize >= 2.6.0 needed by pg_activity-3.1.1-1.rhel8.noarch
```

Probably alternative would be to provide also required python packages in PGDG-common.

**Comment by dlax** [comment]
> nothing provides python3-attrs >=18.1 needed by pg_activity-3.1.1-1.rhel8.noarch

This one is a packaging bug, we have no such lower bound on our side.

> nothing provides python3-humanize >= 2.6.0 needed by pg_activity-3.1.1-1.rhel8.noarch

This is being worked around in #345.

In any case, EPEL would probably be required.

**Comment by krisavi** [comment]
EPEL is not enough on RHEL8. On RHEL8 I doubt they will provide required packages in upstream.

**Comment by dlax** [comment]
> Latest package available in AppStream is python3-humanize-0.5.1-13.el8.noarch.rpm

With which we'll restore compatibility from #354.

> For python3-attrs, the same thing, not available in EPEL, and latest available in AppStream is python3-attrs-17.4.0-6.el8.noarch.rpm

With which we already are compatible; but for which there is a buggy constraint in PGDG packaging as reported [here](https://redmine.postgresql.org/issues/7717#note-5).

Sorry; I apparently confused_ appstream and EPEL. But in any case, I think this can be sorted out.

**Comment by dlax** [comment]
> I tried install through pip but pip installing 2.3.1 too for now.

Which Python version are you using? If you want a recent version of pg_activity, you need at least Python 3.7.

**Comment by bagafoot** [comment]
> > I tried install through pip but pip installing 2.3.1 too for now.
> 
> Which Python version are you using? If you want a recent version of pg_activity, you need at least Python 3.7.

hmm, I got Python 3.6, ok thanks
