### ISSUE TITLE
Ask for new release, including pid bug

### ISSUE THREAD

**Issue by chmuche** [dalibo/pg_activity#333]
Thanks for your work @blogh on the fix of  [https://github.com/dalibo/pg_activity/commit/b016e51](this bug).

Do you plan to release a new version soon, including this fix?

**Comment by blogh** [comment]
Hi, 

Thanks for testing.

Here is the release: https://github.com/dalibo/pg_activity/releases/tag/v3.0.2

**Comment by blogh** [comment]
grr little mypi problem ... should be fixed soon.

**Comment by blogh** [comment]
I had to re-release, but it's on mypi now : 
* https://pypi.org/project/pg-activity/#history
* https://github.com/dalibo/pg_activity/releases/tag/v3.0.3

**Comment by chmuche** [comment]
Thanks a lot :+1:
work like a charm :heart:
