### ISSUE TITLE
Weird display issues inside GNU screen

### ISSUE THREAD

**Issue by esabol** [dalibo/pg_activity#356]
If I start pg_activity inside of an xterm window, I see this:
![Screen Shot 2023-03-15 at 3 53 48 PM](https://user-images.githubusercontent.com/22986767/225436626-069bcc44-784e-4dcf-8a8f-965f2a068bf3.png)
Looks very nice! I think this is how it is supposed to look, although there are no blue dots/bullets between the items at the top. That's probably just be a font issue though. $TERM is "xterm256-color".

If I start GNU screen inside of the same xterm window, I see this:
![Screen Shot 2023-03-15 at 4 01 05 PM](https://user-images.githubusercontent.com/22986767/225428934-4aea3ae6-6cdd-4347-805c-c94d6dd192f9.png)
This doesn't look right. All the items at the top are on separate lines for some reason? And some lines are completely missing, like the database version and server name.

P.S. I figured out why I was getting `â` instead of the bullets/dots in my macOS Terminal window. Terminal profile was set to Latin-1 instead of UTF-8. When I changed it to UTF-8, I got the blue bullets/dots. That said, can you point me to where in the code the blue dots/bullets are printed? I'd like to change that character to something else....

EDIT: Hmmm, using xterm on  RHEL 8.7 with $TERM set to "xterm-color" (not inside of GNU screen), I get blue squares instead of the blue dots/bullets:
![Screen Shot 2023-03-15 at 4 32 59 PM](https://user-images.githubusercontent.com/22986767/225435832-4537ed98-2b63-444b-9241-048e1ddc70b9.png)

**Comment by dlax** [comment]
I can't reproduce (don't use macOS, nor RHEL directly myself); but will fix through #357.

**Comment by dlax** [comment]
See also #230

**Comment by esabol** [comment]
> I can't reproduce (don't use macOS, nor RHEL directly myself); but will fix through #357.

You started pg_activity inside of GNU screen and couldn't reproduce what I'm seeing?

**Comment by dlax** [comment]
> You started pg_activity inside of GNU screen and couldn't reproduce what I'm seeing in the second screenshot? I don't think this has anything to do with macOS or RHEL....

Yes; that's what I did. Even tried in a Linux virtual console, where I could indeed notice that the blue dots were not rendering well (quite similarly to your third screenshot); in fact, the "blue dots issue" happens on this virtual console even without screen, so it's unrelated to screen I think.

Can you try if #357 resolves the issue of your second screenshot?

**Comment by esabol** [comment]
> Yes; that's what I did.

What version of GNU screen did you try?

> in fact, the "blue dots issue" happens on this virtual console even without screen, so it's unrelated to screen I think.

Yeah, I thought my "P.S." made that clear.

> Can you try if #357 resolves the issue of your second screenshot?

Um, how do I do that? I've tried the following:

`python3 -m pip install "git+https://github.com/...`

**Comment by esabol** [comment]
Ah, I figured it out. It was
```
python3 -m pip install "git+https://github.com/dlax/pg_activity.git@dot" --upgrade --user
```
And it fixed it! pg_activity looks great inside of my GNU screen now!

I was skeptical, but, yeah, that did the trick. Thanks!

**Comment by dlax** [comment]
Version 3.3.0, just released, includes the fix for this issue.

**Comment by esabol** [comment]
> Version 3.3.0, just released, includes the fix for this issue.

Confirmed. Thanks again!
