### ISSUE TITLE
The 'client' column only shows the first 16 characters of IPv6 addresses.

### ISSUE THREAD

**Issue by brainexe** [dalibo/pg_activity#365]
When working with IPv6 connections, the "client" column is only showing the first 16 characters of the client address, which is way too small to identify the client. [Here is the column definition with the fix to display the full IPv6 address](https://github.com/dalibo/pg_activity/blob/25aa3fca8a05d943809f84483f6ef84c6547017b/pgactivity/types.py#L328).

Here is one example:
![Screenshot 2023-03-27 at 14 48 26](https://user-images.githubusercontent.com/1894271/228214602-a35c6e82-ed9e-4b19-9874-c508de8c56e1.png)

I don't have an ultimate solution for this, but a config flag (like --full-client-ip) to show the full client address (opt-in) might be doable and don't show the pretty long addresses by default.

**Comment by dlax** [comment]
@brainexe, we have just released version 3.4.0 which includes support for [UI configuration through a file](https://github.com/dalibo/pg_activity#configuration) so you might want to set:
```ini
[client]
width = 39
```
in one of `~/.config/pg_activity.conf` or `/etc/pg_activity.conf`.

Sorry it took so long to resolve this issue; the idea of a configuration being new, we had to go through a bit more thinking and testing than would have been required to just fix this particular issue.
