### ISSUE TITLE
Any plans to allow for running pg_activity remotely with superuser privileges?

### ISSUE THREAD

**Issue by bryanconlon** [dalibo/pg_activity#375]
We are migrating to Google CloudSQL and you don't get full superuser privileges.  I will miss this tool!

Password:
Traceback (most recent call last):
  File "/usr/bin/pg_activity", line 254, in main
    service=os.environ.get('PGSERVICE'))
  File "/usr/bin/pg_activity", line 416, in pg_connect
    service=service,
  File "/usr/lib/python3.6/site-packages/pgactivity/Data.py", line 163, in pg_connect
    raise Exception("Must be run with database superuser privileges.")
Exception: Must be run with database superuser privileges.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pg_activity", line 439, in <module>
    main()
  File "/usr/bin/pg_activity", line 394, in main
    if debug is True:
UnboundLocalError: local variable 'debug' referenced before assignment

**Comment by blogh** [comment]
hi, Are you using the latest version ?

**Comment by blogh** [comment]
It works (some info are not displayed as stated by the messages):

```
(.venv) [benoit@benoit-dalibo pg_activity]$ psql -c "\du notsuper"
           List of roles
 Role name | Attributes | Member of 
-----------+------------+-----------
 notsuper  |            | {}

(.venv) [benoit@benoit-dalibo pg_activity]$ pg_activity --version
pg_activity 3.4.2
(.venv) [benoit@benoit-dalibo pg_activity]$ pg_activity -U notsuper
INFO - Insufficient privilege to show data_directory. System counters are disabled.
INFO - Insufficient privilege to fetch the tempfile data. The feature was disabled. Please use --no-tempfiles or a platform specific setting (eg. --rds).
```
