### ISSUE TITLE
Dependency errors when updating RHEL 8

### ISSUE THREAD

**Issue by dmonmuc** [dalibo/pg_activity#384]
pg_activity 2.3.1-1.rhel8 depends on python3-attrs 22.1.0-1.rhel8.
While trying to update RHEL 8 you get dependency issues.

Error: Transaction test failed:
 File /usr/lib/python3.9/site-packages/attr/pycache/converters.cpython-39.opt-1.pyc from installation of python39-attrs-22.1.0-1.rhel8.noarch conflicts with file from package python3-attrs-22.1.0-1.rhel8.noarch
 File /usr/lib/python3.9/site-packages/attr/pycache/converters.cpython-39.pyc from installation of python39-attrs-22.1.0-1.rhel8.noarch conflicts with file from package python3-attrs-22.1.0-1.rhel8.noarch

So you have to uninstall pg_activity first to be able to update the system.
Afterwards you can install pg_activity 3.3.0-1.rhel8.
Then you get python39-attrs.noarch 22.1.0-1.rhel8

related problem see https://forums.rockylinux.org/t/error-problem-cannot-install-the-best-update-candidate-for-package-pg-activity-2-3-1-1-rhel8-noarch/9224

**Comment by dlax** [comment]
This is a packaging issue, so as recommended [in the README](https://github.com/dalibo/pg_activity#from-distribution-packages), you should reach the maintainers of the package.



> related problem see https://forums.rockylinux.org/t/error-problem-cannot-install-the-best-update-candidate-for-package-pg-activity-2-3-1-1-rhel8-noarch/9224

... which also recommends to ask the maintainers of the repository.
