### ISSUE TITLE
psycopg3 compatibility?

### ISSUE THREAD

**Issue by gleu** [dalibo/pg_activity#400]
I was wondering if pg_activity is compatible with psycopg3. If no, would it be difficult to move to psycopg3 ?

Thanks.

**Comment by dlax** [comment]
It is compatible with psycopg 3+ already, alongside with psycopg2 as a "legacy" alternative (mostly for distributions): https://github.com/dalibo/pg_activity/blob/master/CHANGELOG.md#pg_activity-310---2023-03-01

**Comment by gleu** [comment]
OK, good to know. It looks like you need python3-typing-extensions RPM package if you want to use psycopg3 with pg_activity. It wasn't needed with psycopg2, but OK, I'm fine with that. Thank you.

**Comment by dlax** [comment]
> It looks like you need python3-typing-extensions RPM package if you want to use psycopg3 with pg_activity.

If you're using the package from yum.postgresql.org, it's a packaging 
bug: https://redmine.postgresql.org/issues/7781

**Comment by gleu** [comment]
Oh, interesting. Thank you. 5-months-without-answer ticket, probably won't move anytime soon :(
