### ISSUE TITLE
columns not visible with terminal in GNOME dark or similar

### ISSUE THREAD

**Issue by jsarola** [dalibo/pg_activity#407]
When using pg_activity with terminal in dark mode, the column's database, app and user are not visible, they use "black_bold" as color and it's not visible.

Could be an option to have two different color profiles? One for dark mode and one for light mode?

![image](https://github.com/dalibo/pg_activity/assets/45364799/fd8408f3-bc7d-4124-a468-6c375f9c4864)

The workaround is modifying colors.py and change black_bold to white_bold in this columns

**Comment by dlax** [comment]
That's something we could implement by [configuration](https://github.com/dalibo/pg_activity?tab=readme-ov-file#configuration). Maybe a global `color_scheme` option with built-in schemes (dark, light) and/or a per-column `color` option.
