### ISSUE TITLE
No queries recorded - cannot get query listed

### ISSUE THREAD

**Issue by paurullan** [dalibo/pg_activity#86]
This may be a problem on usage but I cannot get any query shown on the «running queries» panel.
I open another connection against the database, do queries on my own and the «TPS» value goes up and down but there are no running queries on the list.

I also tried to put the «set log_statement = 'all'» and while it records que queries on the logs they do not show up in the list.

I was thinking that perhards the queries are "too fast" but in the documentation example there are queries in the order of .5ms so it cannot be the case.

How should I proceed?

**Comment by julmon** [comment]
Hi,

The query list pg_activity shows are not coming from postgres logs, so log_statement does not have any effect on its behavior.  This query list is coming from postgres internal view : `pg_stat_activity`.
What postgres doc says about this internal view  : `One row per server process, showing information related to the current activity of that process, such as state and current query. `
So, you'll see only queries running when this list is built.

**Comment by blogh** [comment]
A [FAQ](https://github.com/dalibo/pg_activity#faq) has been added to the README.md to document possible reasons why queries might not show.

If you have more question on this topic feel free to reopen the issue.
