### ISSUE TITLE
full/indented view modes cut off the start of additional lines

### ISSUE THREAD

**Issue by BenLubar** [dalibo/pg_activity#88]
I'm assuming the documentation has the list of view modes in the wrong order, because it seems to default to full:
![image](https://user-images.githubusercontent.com/4257305/45000586-c843c680-af8b-11e8-98a3-29c25f1372e8.png)

and pushing v once switches to indented:
![image](https://user-images.githubusercontent.com/4257305/45000572-a9ddcb00-af8b-11e8-95cf-929bb47d9fd5.png)

and then pushing v a third time switches to truncated (only the first line of each query).

It seems that lines in the query after the first are missing characters from the start of each line.

I'm running pg_activity inside of tmux if that makes a difference.

The queries in these screenshots are from here: https://github.com/BenLubar/nodebb-postgres-converter/tree/f66834c5a07c07776abc2a0d13487c198036456e

**Comment by julmon** [comment]
Hi,

I guess this commit https://github.com/julmon/pg_activity/commit/d83cb15d20d1226c0379a56e16fdf18c8d86b0c8 fix this case.

**Comment by blogh** [comment]
The README was fixed to reflect the order in pg_activity.
